openapi: 3.0.1
info:
  title: Pets.WebApi
  version: '1.0'
paths:
  /api/Pet:
    get:
      tags:
        - Pet
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PetListVm'
            application/json:
              schema:
                $ref: '#/components/schemas/PetListVm'
            text/json:
              schema:
                $ref: '#/components/schemas/PetListVm'
    post:
      tags:
        - Pet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePetDto'
          text/json:
            schema:
              $ref: '#/components/schemas/CreatePetDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreatePetDto'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                format: uuid
            application/json:
              schema:
                type: string
                format: uuid
            text/json:
              schema:
                type: string
                format: uuid
    put:
      tags:
        - Pet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePetDto'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdatePetDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdatePetDto'
      responses:
        '200':
          description: OK
  /api/Pet/{id}:
    get:
      tags:
        - Pet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PetDetailVm'
            application/json:
              schema:
                $ref: '#/components/schemas/PetDetailVm'
            text/json:
              schema:
                $ref: '#/components/schemas/PetDetailVm'
    delete:
      tags:
        - Pet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
components:
  schemas:
    CreatePetDto:
      type: object
      properties:
        age:
          type: integer
          format: int32
        price:
          type: number
          format: double
        birthday:
          type: string
          format: date-time
        description:
          type: string
          nullable: true
      additionalProperties: false
    PetDetailVm:
      type: object
      properties:
        id:
          type: integer
          format: int32
        age:
          type: integer
          format: int32
        price:
          type: number
          format: double
        birthday:
          type: string
          format: date-time
        description:
          type: string
          nullable: true
      additionalProperties: false
    PetDto:
      type: object
      properties:
        age:
          type: integer
          format: int32
        price:
          type: number
          format: double
        birthday:
          type: string
          format: date-time
        description:
          type: string
          nullable: true
      additionalProperties: false
    PetListVm:
      type: object
      properties:
        pets:
          type: array
          items:
            $ref: '#/components/schemas/PetDto'
          nullable: true
      additionalProperties: false
    UpdatePetDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        age:
          type: integer
          format: int32
        price:
          type: number
          format: double
        birthday:
          type: string
          format: date-time
        description:
          type: string
          nullable: true
      additionalProperties: false
